server:
  port: 18081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Kute110@

  application:
    name: pure-order-app
